### ISSUE TITLE
Grid folder views from dock collapse as mouse is moved.

### ISSUE THREAD

**Issue by samholmes** [sbmpost/AutoRaise#141]
How I'm building it:

```
make clean && make CXXFLAGS="-DOLD_ACTIVATION_METHOD -DEXPERIMENTAL_FOCUS_FIRST" && make install
```

I'm on latest commit: 39d854a46e2e5ab058dc16ac3bda28f400412613

Issue:

If I click Downloads from the Dock and it brings up a grid folder view for that folder, and then I move my mouse cursor to the over the grid, it will collapse if the cursor enters new window boundaries underneath the grid view.

**Comment by sbmpost** [comment]
@samholmes 
Can you try with [this branch](https://github.com/sbmpost/AutoRaise/archive/refs/heads/fix-downloads-hiding.zip)?

Note that the mouseStop option has been removed for a while now. The same effect is achieved by having focusDelay > 1 which is what you have configured.

**Comment by samholmes** [comment]
@sbmpost Instead of a zip, can you send me the branch so I can check it out on my local repo?

**Comment by sbmpost** [comment]
@samholmes 

https://github.com/sbmpost/AutoRaise/branches/fix-downloads-hiding/

**Comment by samholmes** [comment]
This branch appears to have fixed the issue somewhat. Any windows underneath the dock's grid window thing will not trigger enter/exit events. However, it looks like if my cursor hovers over a window outside of the dock's grid view thingy, then enter/exit events are tracked. I wouldn't want any enter/exit events to be enabled because if they are then the dock grid goes away. If we can keep the dock grid from collapsing, then it shouldn't matter if the windows get focus at all. That seems to be the problem here.

**Comment by sbmpost** [comment]
@samholmes 

> This branch appears to have fixed the issue somewhat

I have pushed once more. should be fixed completely now ;-)

**Comment by samholmes** [comment]
This fixes it the problem. However, it would be ideal to allow for focus change without closing the dock grid, but that might not be possible I guess. Please let me know when this PR merges!

**Comment by sbmpost** [comment]
@samholmes 

> but that might not be possible I guess.

Correct. If you would click another without AutoRaise enabled, the downloads window would also disappear.

The question is what behavior is better:

1. Hide the downloads window as soon as the mouse leaves it, so you can focus other apps

2. Downloads window stays focused for as long as you don't click another window, in effect temporarily disabling AutoRaise (so what has been implemented atm).

Thoughts?

**Comment by samholmes** [comment]
My thought is the downloads window should remain open until clicked outside of it. The focus of other windows can still happen if you enter those windows outside of the downloads window, but this shouldn't collapse the downloads window. My thought is that the action of "focusing" a window does not bring it to front nor collapse it (in the case of the download window). Focusing just changes the OS menu bar and keyboard input to the currently focused window. Only clicking can bring the window to front or collapse it if it's ephemeral like a downloads window or context menu dropdown kind of thing.

**Comment by sbmpost** [comment]
@samholmes 

So option 2 if I read correctly.
